name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Saludos
      run: echo Hola cuando se hace push!
    - name: multiline
      env:
          DOCKER_USER: ${{ secrets.DOCKER_USRER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker -v
        docker build . -t anix117/gitactnodejs:200524
        docker images
        echo 'Docker login'
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        docker push anix117/gitactnodejs:200524
