name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Saludos
      run: echo Hola cuando se hace push!
    - name: multiline
      run: |
        docker -v
        docker build . -d anix117/gitactnodejs:200524
        docker images
        docker run anix117/gitactnodejs:200524
        docker ps -a 
